<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<span class="actions">
    <?php $_order = $block->getOrder() ?>
    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?=
        /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
        </a>
    <?php endif ?>

    <?= $block->getChildHtml() ?>
</span>
