<div class="block block-order-details-view">
	<div class="block-title">
        <strong><?= __('Details of your order') ?></strong>
    </div>
    <div class="block-content">
    	<dt class="title"><?= __('Status') ?></dt>
    	<dd class="content">
            <table class="data">
                    <tbody>
                    	<tr>
                            <th scope="row" class="middle"><?= $block->getChildHtml('order.status.current'); ?></th>
                            <?php if($block->getOrder()->getState() == 'canceled'): ?>
    							<td  class="middle">
    								<?= $block->getChildHtml('buttons'); ?>
    							</td>
    						<?php endif; ?>
                    	</tr>
                    </tbody>
            </table>
    </div>
</div>
<?= $block->getChildHtml('order.status.comments'); ?>